from __future__ import annotations

from .models import EmailExample, TaskDefinition

TASKS: list[TaskDefinition] = [
    TaskDefinition(
        task_id=1,
        name="easy",
        description="Classify email category.",
        required_fields=["category"],
        level="easy",
    ),
    TaskDefinition(
        task_id=2,
        name="medium",
        description="Classify email category and priority.",
        required_fields=["category", "priority"],
        level="medium",
    ),
    TaskDefinition(
        task_id=3,
        name="hard",
        description="Classify, prioritize, route, and choose the action.",
        required_fields=["category", "priority", "department", "action"],
        level="hard",
    ),
]

DATASET: list[EmailExample] = [
    EmailExample(
        email_id="em-001",
        sender="billing@shopnova.com",
        subject="Charged twice for order 88412",
        email_text="I was charged twice for my order 88412. Please fix the duplicate billing and refund the second charge.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-002",
        sender="help@cloudsuite.com",
        subject="Login issue on my account",
        email_text="I cannot log in after the password reset. The page keeps timing out and I need help ASAP.",
        category="support",
        priority="high",
        department="support_team",
        action="reply",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-003",
        sender="trial@dealstream.io",
        subject="Trial issue and pricing question",
        email_text="We want pricing for a team plan, but the trial keeps failing with a login issue and we need help choosing the right next step.",
        category="support",
        priority="medium",
        department="support_team",
        action="reply",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "mixed_intent"],
    ),
    EmailExample(
        email_id="em-004",
        sender="no-reply@newsletter.example",
        subject="Weekly product digest",
        email_text="Here are this week's updates, feature announcements, and webinar reminders.",
        category="spam",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-005",
        sender="ceo-office@acme.internal",
        subject="Board deck final review",
        email_text="Please review the attached board deck before the executive meeting at 4 PM.",
        category="internal",
        priority="medium",
        department="ignore",
        action="reply",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-006",
        sender="payments@marketplace.app",
        subject="Money back for incorrect billing",
        email_text="We need money back for an incorrect billing charge, but the account also shows a login issue after the payment reset.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "billing_support_overlap"],
    ),
    EmailExample(
        email_id="em-007",
        sender="customer@retailmail.com",
        subject="Not urgent but the system is completely down",
        email_text="Not urgent but the system is completely down and we cannot finish the order review, please help if this is on your side.",
        category="support",
        priority="high",
        department="support_team",
        action="escalate",
        difficulty="hard",
        tags=["adversarial_phrasing", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-008",
        sender="enterprise@saasgrowth.com",
        subject="Pricing question and rollout blocker",
        email_text="We are comparing pricing, but the rollout is blocked by a bug and a support agent might need to confirm the next step.",
        category="sales",
        priority="high",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "sales_support_overlap"],
    ),
    EmailExample(
        email_id="em-009",
        sender="spam-bot@unknown.xyz",
        subject="You won a gift card",
        email_text="Claim your free gift card by clicking this link and enter your account password immediately.",
        category="spam",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="medium",
    ),
    EmailExample(
        email_id="em-010",
        sender="finance-team@northwind.com",
        subject="Policy update with access issue",
        email_text="Please note the new policy update, but some users also report they cannot access the portal after the change.",
        category="internal",
        priority="medium",
        department="ignore",
        action="reply",
        difficulty="hard",
        tags=["ambiguous", "cross_category"],
    ),
    EmailExample(
        email_id="em-011",
        sender="support@streamline.dev",
        subject="Not urgent but checkout is down",
        email_text="Not urgent maybe, but checkout is completely down and the bug is affecting orders across teams.",
        category="support",
        priority="high",
        department="support_team",
        action="escalate",
        difficulty="hard",
        tags=["adversarial_phrasing", "priority_conflict", "noise"],
    ),
    EmailExample(
        email_id="em-012",
        sender="billing@ridefast.ai",
        subject="Annual plan renewal question",
        email_text="I need an updated invoice and want to confirm whether the annual renewal includes tax adjustments.",
        category="billing",
        priority="medium",
        department="finance",
        action="reply",
        difficulty="medium",
    ),
    EmailExample(
        email_id="em-013",
        sender="sales@startupboost.com",
        subject="Proposal request and account issue",
        email_text="We need a proposal for seats and also have an account issue after a password reset, so please route this carefully.",
        category="sales",
        priority="high",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "sales_support_overlap"],
    ),
    EmailExample(
        email_id="em-014",
        sender="security@corp.local",
        subject="URGENT: approve VPN access",
        email_text="Need approval for VPN access before the compliance audit begins today.",
        category="internal",
        priority="high",
        department="ignore",
        action="escalate",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-015",
        sender="alerts@service.status",
        subject="Service outage notification",
        email_text="The upstream provider is down and several customers are reporting login failures.",
        category="support",
        priority="high",
        department="support_team",
        action="escalate",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-016",
        sender="unknown@click-now.me",
        subject="Re: your invoice attached",
        email_text="Please see the attached invoice. Open the file to confirm payment details immediately.",
        category="spam",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-017",
        sender="billing@alphahealth.com",
        subject="Refund request for duplicate subscription",
        email_text="We subscribed twice by mistake during procurement and need the duplicate amount refunded.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-018",
        sender="partner@channel.example",
        subject="Partnership ask with invoice confusion",
        email_text="Could we discuss a partnership next month, but the invoice also looks wrong and we need the accounting team to review it.",
        category="sales",
        priority="medium",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category"],
    ),
    EmailExample(
        email_id="em-019",
        sender="employee@acme.internal",
        subject="Kitchen supplies running low",
        email_text="The office kitchen needs more coffee filters and paper towels for next week.",
        category="internal",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-020",
        sender="support@mobileapp.io",
        subject="Login issue after payment",
        email_text="The SMS code never arrives after payment and the customer is stuck at onboarding, maybe a billing side issue.",
        category="support",
        priority="high",
        department="support_team",
        action="reply",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "billing_support_overlap"],
    ),
    EmailExample(
        email_id="em-021",
        sender="billing@conferencehub.net",
        subject="Need tax invoice urgently",
        email_text="Our accounting team needs a tax invoice today to close the monthly books.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="easy",
    ),
    EmailExample(
        email_id="em-022",
        sender="teamlead@internal.tools",
        subject="Launch checklist review",
        email_text="Please confirm the launch checklist and send feedback before we publish the release notes.",
        category="internal",
        priority="medium",
        department="ignore",
        action="reply",
        difficulty="medium",
    ),
    EmailExample(
        email_id="em-023",
        sender="sales@bigdeal.co",
        subject="Need proposal but our login is failing",
        email_text="We want a proposal for 500 seats, but the admin login is failing and we need help before we can buy.",
        category="sales",
        priority="high",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-024",
        sender="marketing@mailer.vip",
        subject="Congratulations, you have been selected",
        email_text="This is not a spam message? Claim your prize by opening the attached coupon now.",
        category="spam",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-025",
        sender="billing@traveldesk.com",
        subject="I think I was charged twice",
        email_text="I think I was charged twice but I am not sure if it was my bank or your system.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
        noisy_text="I th!nk I was char ged tw1ce but not sure if it was my bank.",
    ),
    EmailExample(
        email_id="em-026",
        sender="support@deliverypro.co",
        subject="Package status seems off",
        email_text="Can you check my order? It has not arrived but tracking says delivered.",
        category="support",
        priority="high",
        department="support_team",
        action="reply",
        difficulty="hard",
        noisy_text="Can you chek my order? tracking says delivred.",
    ),
    EmailExample(
        email_id="em-027",
        sender="employee@acme.internal",
        subject="Might be urgent system issue",
        email_text="This might be urgent, not sure if it is a system issue or user error.",
        category="internal",
        priority="high",
        department="ignore",
        action="escalate",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-028",
        sender="sales@cloudvalue.io",
        subject="Buy pricing details for 300 seats",
        email_text="We would like to buy and compare price options for 300 seats across teams.",
        category="sales",
        priority="medium",
        department="sales_team",
        action="forward",
        difficulty="medium",
    ),
    EmailExample(
        email_id="em-029",
        sender="spam-offers@promo.cash",
        subject="Unsubscribe from this offer now",
        email_text="Unsubscribe if you do not want this offer and coupon spam anymore.",
        category="spam",
        priority="low",
        department="ignore",
        action="archive",
        difficulty="medium",
    ),
    EmailExample(
        email_id="em-030",
        sender="helpdesk@warehouse.app",
        subject="Could be a bug in checkout",
        email_text="The checkout bug may be causing payment errors on multiple carts.",
        category="support",
        priority="medium",
        department="support_team",
        action="escalate",
        difficulty="hard",
    ),
    EmailExample(
        email_id="em-031",
        sender="billing@megafoods.com",
        subject="Invoice still pending with bank",
        email_text="I already paid, but the bank says pending. Can you check whether this needs a refund or just a statement update?",
        category="billing",
        priority="medium",
        department="finance",
        action="reply",
        difficulty="hard",
        thread_id="billing-pending",
        tags=["priority_conflict", "ambiguous"],
    ),
    EmailExample(
        email_id="em-032",
        sender="billing@megafoods.com",
        subject="Urgent: same invoice issue is blocking closeout",
        email_text="Same invoice is still pending and our month-end close is blocked today. Please help right away.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
        thread_id="billing-pending",
        tags=["priority_conflict", "ambiguous"],
    ),
    EmailExample(
        email_id="em-033",
        sender="support@portal.io",
        subject="Maybe user error or a browser bug",
        email_text="The dashboard might be broken or the browser cache is stale, I am not fully sure.",
        category="support",
        priority="medium",
        department="support_team",
        action="reply",
        difficulty="hard",
        thread_id="portal-issue",
        tags=["ambiguous", "noise"],
        noisy_text="The dashb0ard might be br0ken or cache stale.",
    ),
    EmailExample(
        email_id="em-034",
        sender="support@portal.io",
        subject="Same portal bug is now blocking multiple teams",
        email_text="The same login bug is affecting everyone and needs attention today.",
        category="support",
        priority="high",
        department="support_team",
        action="escalate",
        difficulty="hard",
        thread_id="portal-issue",
        tags=["priority_conflict", "ambiguous"],
    ),
    EmailExample(
        email_id="em-035",
        sender="ops@warehousepay.com",
        subject="refnd plz asap!! double chrgd??",
        email_text="refnd plz asap!! double chrgd?? We think the payment went through twice, but the system also says the order is on hold.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
        noisy_text="refnd plz asap!! double chrgd??",
        tags=["noise", "ambiguous", "adversarial_phrasing"],
    ),
    EmailExample(
        email_id="em-036",
        sender="customer@shopcraft.io",
        subject="Not urgent but package issue",
        email_text="Not urgent, but the package still has not arrived and tracking says delivered. We need a status check.",
        category="support",
        priority="high",
        department="support_team",
        action="reply",
        difficulty="hard",
        tags=["adversarial_phrasing", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-037",
        sender="sales@regionwide.com",
        subject="buy price? maybe support too",
        email_text="We want to buy, but the trial account is broken and we cannot log in to review the pricing sheet.",
        category="sales",
        priority="medium",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "noise"],
    ),
    EmailExample(
        email_id="em-038",
        sender="internal@acme.local",
        subject="System is down but just a heads up",
        email_text="Just a heads up that the system is completely down and multiple teams are blocked, so please escalate when you can.",
        category="internal",
        priority="high",
        department="ignore",
        action="escalate",
        difficulty="hard",
        tags=["adversarial_phrasing", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-039",
        sender="sales@northstar.io",
        subject="Pricing for 200 seats but login is blocked",
        email_text="We want pricing for 200 seats, but one admin is blocked by a login issue and we need a quote today.",
        category="sales",
        priority="high",
        department="sales_team",
        action="forward",
        difficulty="hard",
        tags=["ambiguous", "cross_category", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-040",
        sender="billing@ledgerworks.com",
        subject="Invoice still pending for month-end close",
        email_text="Our invoice is still pending with the bank and month-end close is blocked today. Please check whether this needs a refund or statement update.",
        category="billing",
        priority="high",
        department="finance",
        action="reply",
        difficulty="hard",
        tags=["priority_conflict", "ambiguous"],
    ),
    EmailExample(
        email_id="em-041",
        sender="operations@acme.local",
        subject="Compliance audit and board deck review",
        email_text="Please review the board deck before the compliance audit today; the release is blocked until approval.",
        category="internal",
        priority="high",
        department="ignore",
        action="escalate",
        difficulty="hard",
        tags=["ambiguous", "priority_conflict"],
    ),
    EmailExample(
        email_id="em-042",
        sender="support@portalops.io",
        subject="Portal bug affecting multiple teams",
        email_text="The same portal bug is affecting everyone and the system is down, so please escalate immediately.",
        category="support",
        priority="high",
        department="support_team",
        action="escalate",
        difficulty="hard",
        tags=["priority_conflict", "adversarial_phrasing"],
    ),
]


def get_task_definition(task_id: int) -> TaskDefinition:
    for task in TASKS:
        if task.task_id == task_id:
            return task
    raise ValueError(f"Unknown task_id: {task_id}")


def get_email_by_id(email_id: str) -> EmailExample:
    for email in DATASET:
        if email.email_id == email_id:
            return email
    raise ValueError(f"Unknown email_id: {email_id}")
